// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ec2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEC2Client creates a new instance of MockEC2Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEC2Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEC2Client {
	mock := &MockEC2Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEC2Client is an autogenerated mock type for the EC2Client type
type MockEC2Client struct {
	mock.Mock
}

type MockEC2Client_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEC2Client) EXPECT() *MockEC2Client_Expecter {
	return &MockEC2Client_Expecter{mock: &_m.Mock}
}

// CreateFleet provides a mock function for the type MockEC2Client
func (_mock *MockEC2Client) CreateFleet(ctx context.Context, params *ec2.CreateFleetInput, optFns ...func(*ec2.Options)) (*ec2.CreateFleetOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateFleet")
	}

	var r0 *ec2.CreateFleetOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.CreateFleetInput, ...func(*ec2.Options)) (*ec2.CreateFleetOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.CreateFleetInput, ...func(*ec2.Options)) *ec2.CreateFleetOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.CreateFleetOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.CreateFleetInput, ...func(*ec2.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEC2Client_CreateFleet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFleet'
type MockEC2Client_CreateFleet_Call struct {
	*mock.Call
}

// CreateFleet is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ec2.CreateFleetInput
//   - optFns ...func(*ec2.Options)
func (_e *MockEC2Client_Expecter) CreateFleet(ctx any, params any, optFns ...any) *MockEC2Client_CreateFleet_Call {
	return &MockEC2Client_CreateFleet_Call{Call: _e.mock.On("CreateFleet",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockEC2Client_CreateFleet_Call) Run(run func(ctx context.Context, params *ec2.CreateFleetInput, optFns ...func(*ec2.Options))) *MockEC2Client_CreateFleet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.CreateFleetInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.CreateFleetInput)
		}
		var arg2 []func(*ec2.Options)
		var variadicArgs []func(*ec2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ec2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEC2Client_CreateFleet_Call) Return(createFleetOutput *ec2.CreateFleetOutput, err error) *MockEC2Client_CreateFleet_Call {
	_c.Call.Return(createFleetOutput, err)
	return _c
}

func (_c *MockEC2Client_CreateFleet_Call) RunAndReturn(run func(ctx context.Context, params *ec2.CreateFleetInput, optFns ...func(*ec2.Options)) (*ec2.CreateFleetOutput, error)) *MockEC2Client_CreateFleet_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeInstances provides a mock function for the type MockEC2Client
func (_mock *MockEC2Client) DescribeInstances(ctx context.Context, params *ec2.DescribeInstancesInput, optFns ...func(*ec2.Options)) (*ec2.DescribeInstancesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeInstances")
	}

	var r0 *ec2.DescribeInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeInstancesInput, ...func(*ec2.Options)) (*ec2.DescribeInstancesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeInstancesInput, ...func(*ec2.Options)) *ec2.DescribeInstancesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.DescribeInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.DescribeInstancesInput, ...func(*ec2.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEC2Client_DescribeInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeInstances'
type MockEC2Client_DescribeInstances_Call struct {
	*mock.Call
}

// DescribeInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ec2.DescribeInstancesInput
//   - optFns ...func(*ec2.Options)
func (_e *MockEC2Client_Expecter) DescribeInstances(ctx any, params any, optFns ...any) *MockEC2Client_DescribeInstances_Call {
	return &MockEC2Client_DescribeInstances_Call{Call: _e.mock.On("DescribeInstances",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockEC2Client_DescribeInstances_Call) Run(run func(ctx context.Context, params *ec2.DescribeInstancesInput, optFns ...func(*ec2.Options))) *MockEC2Client_DescribeInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.DescribeInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.DescribeInstancesInput)
		}
		var arg2 []func(*ec2.Options)
		var variadicArgs []func(*ec2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ec2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEC2Client_DescribeInstances_Call) Return(describeInstancesOutput *ec2.DescribeInstancesOutput, err error) *MockEC2Client_DescribeInstances_Call {
	_c.Call.Return(describeInstancesOutput, err)
	return _c
}

func (_c *MockEC2Client_DescribeInstances_Call) RunAndReturn(run func(ctx context.Context, params *ec2.DescribeInstancesInput, optFns ...func(*ec2.Options)) (*ec2.DescribeInstancesOutput, error)) *MockEC2Client_DescribeInstances_Call {
	_c.Call.Return(run)
	return _c
}

// RunInstances provides a mock function for the type MockEC2Client
func (_mock *MockEC2Client) RunInstances(ctx context.Context, params *ec2.RunInstancesInput, optFns ...func(*ec2.Options)) (*ec2.RunInstancesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RunInstances")
	}

	var r0 *ec2.RunInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.RunInstancesInput, ...func(*ec2.Options)) (*ec2.RunInstancesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.RunInstancesInput, ...func(*ec2.Options)) *ec2.RunInstancesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.RunInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.RunInstancesInput, ...func(*ec2.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEC2Client_RunInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInstances'
type MockEC2Client_RunInstances_Call struct {
	*mock.Call
}

// RunInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ec2.RunInstancesInput
//   - optFns ...func(*ec2.Options)
func (_e *MockEC2Client_Expecter) RunInstances(ctx any, params any, optFns ...any) *MockEC2Client_RunInstances_Call {
	return &MockEC2Client_RunInstances_Call{Call: _e.mock.On("RunInstances",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockEC2Client_RunInstances_Call) Run(run func(ctx context.Context, params *ec2.RunInstancesInput, optFns ...func(*ec2.Options))) *MockEC2Client_RunInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.RunInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.RunInstancesInput)
		}
		var arg2 []func(*ec2.Options)
		var variadicArgs []func(*ec2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ec2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEC2Client_RunInstances_Call) Return(runInstancesOutput *ec2.RunInstancesOutput, err error) *MockEC2Client_RunInstances_Call {
	_c.Call.Return(runInstancesOutput, err)
	return _c
}

func (_c *MockEC2Client_RunInstances_Call) RunAndReturn(run func(ctx context.Context, params *ec2.RunInstancesInput, optFns ...func(*ec2.Options)) (*ec2.RunInstancesOutput, error)) *MockEC2Client_RunInstances_Call {
	_c.Call.Return(run)
	return _c
}

// TerminateInstances provides a mock function for the type MockEC2Client
func (_mock *MockEC2Client) TerminateInstances(ctx context.Context, params *ec2.TerminateInstancesInput, optFns ...func(*ec2.Options)) (*ec2.TerminateInstancesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for TerminateInstances")
	}

	var r0 *ec2.TerminateInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.TerminateInstancesInput, ...func(*ec2.Options)) (*ec2.TerminateInstancesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.TerminateInstancesInput, ...func(*ec2.Options)) *ec2.TerminateInstancesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.TerminateInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.TerminateInstancesInput, ...func(*ec2.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEC2Client_TerminateInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TerminateInstances'
type MockEC2Client_TerminateInstances_Call struct {
	*mock.Call
}

// TerminateInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ec2.TerminateInstancesInput
//   - optFns ...func(*ec2.Options)
func (_e *MockEC2Client_Expecter) TerminateInstances(ctx any, params any, optFns ...any) *MockEC2Client_TerminateInstances_Call {
	return &MockEC2Client_TerminateInstances_Call{Call: _e.mock.On("TerminateInstances",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockEC2Client_TerminateInstances_Call) Run(run func(ctx context.Context, params *ec2.TerminateInstancesInput, optFns ...func(*ec2.Options))) *MockEC2Client_TerminateInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.TerminateInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.TerminateInstancesInput)
		}
		var arg2 []func(*ec2.Options)
		var variadicArgs []func(*ec2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ec2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEC2Client_TerminateInstances_Call) Return(terminateInstancesOutput *ec2.TerminateInstancesOutput, err error) *MockEC2Client_TerminateInstances_Call {
	_c.Call.Return(terminateInstancesOutput, err)
	return _c
}

func (_c *MockEC2Client_TerminateInstances_Call) RunAndReturn(run func(ctx context.Context, params *ec2.TerminateInstancesInput, optFns ...func(*ec2.Options)) (*ec2.TerminateInstancesOutput, error)) *MockEC2Client_TerminateInstances_Call {
	_c.Call.Return(run)
	return _c
}
